export default {
  'Chapter2 Spelling Conventions': {
    title: '2.1 Common spelling',
    desc: 'The following spellings are common to the United States and the United Kingdom, and will not reduce points in the exam. Both left and right spellings are acceptable.',
    columns: ['British', 'American', 'Meaning'],
    rows: [
      ['acknowledgement', 'acknowledgment, acknowledgement', 'acknowledge; thank you'],
      ['adviser', 'advisor', 'consultant'],
      ['ageing', 'aging', 'Aged; old; obsolete'],
      ['aeroplane', 'airplane', 'airplane'],
      ['aluminium', 'aluminum', 'aluminum'],
      ['analogue', 'analog', 'Similarity; analogue; equivalent'],
      ['annex, annexe', 'annex', 'v. annex; annex; seize. n. Ancillary building; additional building'],
      ['apologize, apologise', 'apologize', 'Apologize'],
      ['archaeology', 'archeology, archaeology', 'archeology'],
      ['artefact', 'artifact, artefact', 'artifact; handicraft'],
      ['axe', 'ax, axe', 'ax'],
      ['analyse, analyze', 'analyze', 'analyze'],
      ['behaviour', 'behavior', 'behavior; behavior'],
      ['cancelled', 'canceled, cancelled', 'cancel; terminate; revoke'],
      ['catalogue', 'catalog', 'n. Catalog; directory; a series of (bad things). v. record; catalog...'],
      ['centre', 'center', 'center; center'],
      ['cheque', 'check', 'Cheque'],
      ['chilli, chili', 'chili', 'chili'],
      ['colour', 'color', 'color'],
      ['cosy', 'cozy', '(especially a building that is small and warm) cozy; warm and comfortable; pleasant; comfortable'],
      ['counsellor', 'counselor', 'consultant; counselor; lawyer'],
      ['critcise, critcize', 'criticize', 'criticize; accuse; comment'],
      ['defence', 'defense', 'defense; defence'],
      ['dialogue', 'dialog', 'dialogue; dialogue'],
      ['disc, disk', 'disk', 'disc; disc'],
      ['doughnut', 'donut, doughnut', 'Donuts'],
      ['emphasise', 'emphasize', 'emphasize; attach importance to; make prominent; make obvious'],
      ['enquiry, inquiry', 'inquiry', 'inquire; inquire; investigate; research'],
      ['enrol', 'enroll', 'to join; to register; to enroll; to absorb'],
      ['favour', 'favor', 'support; approval; help; favor'],
      ['fibre', 'fiber', 'fiber; silk; cellulose; quality'],
      ['flavour', 'flavor', 'flavor; characteristics'],
      ['fulfil', 'fulfill, fulfil', 'achieve; achieve; satisfy'],
      ['glamour', 'glamour, glamor', 'attraction; charm; allure'],
      ['grey', 'gray', 'gray; gloomy'],
      ['harbour', 'harbor', 'port'],
      ['honour', 'honor', 'reputation; honor'],
      ['jail, gaol', 'jail', 'prison; jail'],
      ['jewellery', 'jewelry', 'jewelry; jewelry'],
      ['judgement', 'judgment', 'judgment;judgment;judgment'],
      ['kerb', 'curb', 'n. Curb (of a road)'],
      ['kilometre', 'kilometer', 'Kilometer; kilometer'],
      ['labour', 'labor', 'labor; labor'],
      ['licence', 'license', 'permission; license'],
      ['litre', 'liter', 'Lift'],
      ['manoeuvre', 'maneuver', 'n. Fine movements; military exercises; skills; tricks. v. Manipulate; control'],
      ['metre', 'meter', 'rice'],
      ['mould', 'mold', 'mold; mold'],
      ['naught', 'nought', 'none; none; zero'],
      ['neighbour', 'neighbor', 'neighbor; neighboring country'],
      ['offence', 'offense', 'crime; offend'],
      ['organisation', 'organization', 'organization; institution'],
      ['parlour', 'parlor', 'store; store; living room; living room'],
      ['plough', 'plow', 'n. plow. v. plow; plow'],
      ['practise', 'practice', 'v. implement; practice'],
      ['practice', 'practice', 'n. custom; routine; training'],
      ['pyjamas', 'pajamas', 'pajama pants'],
      ['realise', 'realize', 'Understand; realize; realize; realize'],
      ['rigour', 'rigor', 'Strict; strict; strict; strict; meticulous'],
      ['saviour', 'savior', 'rescuer; savior'],
      ['savour', 'savor', 'v. Savor; enjoy. n. fun; interest'],
      ['sceptical', 'skeptical', 'skeptical; skeptical'],
      ['skilfu', 'skillful, skilful', 'skilled; outstanding'],
      ['speciality', 'specialty', '(Note that the pronunciation of the two words is different) specialty; expertise'],
      ['sulphur', 'sulfur', 'sulfur; sulfur'],
      ['theatre', 'theater', 'theater; cinema; script'],
      ['traveller', 'traveler', 'traveler; tourist'],
      ['travelling', 'traveling, travelling', 'travel; itinerant'],
      ['tyre', 'tire', 'tire'],
      ['vice', 'vise, vice', 'deputy; degenerate; bad habits'],
      ['vigour', 'vigor', 'physical strength; vitality; vigor; momentum; power'],
      ['woollen', 'woolen', 'made of wool'],
    ],
  },
}
