const sentences = [
  {
    no: null,
    title: 'Simple subject-verb-object structure',
  },
  {
    no: 1,
    sentence: 'Regular exercise will improve people's self-confidence',
    translationFromBook: 'Regular exercise can increase one\'s self-confidence',
    chatgpt: 'Frequently exercising can increase one\'s confidence',
    remark: '',
  },
  {
    no: 2,
    sentence: 'Teaching quality has a great impact on student performance',
    translationFromBook: 'The quality of teaching can make huge difference to students\' academic performance',
    chatgpt: 'Academic achievement is heavily dependent on the quality of teaching',
    remark: '',
  },
  {
    no: 3,
    sentence: 'Parents and teachers should work hard to reduce the time children watch TV',
    translationFromBook: 'Parents and teachers should make an effort to limit children’s screen time',
    chatgpt: 'Parents and teachers should make efforts to reduce the screen time of children',
    remark: '',
  },
  {
    no: 4,
    sentence: 'An economic slowdown leads to an increase in unemployment',
    translationFromBook: 'The economic slowdown has led to a climbing unemployment rate.',
    chatgpt: 'The economic slowdown has led to an increase in the unemployment rate',
    remark: 'increase itself has a noun part of speech',
  },
  {
    no: 5,
    sentence: 'Economic development requires young workers',
    translationFromBook: 'A country\'s economic development relies on a supply of young workers',
    chatgpt: 'Economic development requires young laborers',
    remark: 'labors 和 laborers 的区别：前者侧重劳动的行为或者劳动力的总称，后者专指从事劳动的人',
  },
  {
    no: 6,
    sentence: '工作量大的人没有时间去休息',
    translationFromBook: 'People with a heavy workload do not have adequate time to rest',
    chatgpt: 'People with heavy workloads often don\'t have time to rest',
    remark: 'adequate adj. Sufficient, qualified. Antonyms for inadequate',
  },
  {
    no: 7,
    sentence: 'In China, many students have to study in the evening',
    translationFromBook: 'A large number of students in China have to do self-study at night',
    chatgpt: 'Many students in China have to attend evening self-study sessions',
    remark: 'self-study self-study',
  },
  {
    no: 8,
    sentence: 'Cultural heritage sites are threatened by urban development',
    translationFromBook: 'The development of cities has posed a threat to heritage sites',
    chatgpt: 'Cultural heritage sites are threatened by urban development',
    remark: 'pose a threat pose a threat',
  },
  {
    no: 9,
    sentence: 'We cannot ignore face-to-face communication',
    translationFromBook: 'We should not ignore face-to-face communication',
    chatgpt: 'We cannot ignore face-to-face communication',
    remark: 'Communication is uncountable when it comes to communicating and communicating.',
  },
  {
    no: 10,
    sentence: 'It is difficult for some public services to balance their budgets',
    translationFromBook: 'Some public services have problems in breaking even',
    chatgpt: 'Some public services are challenging to achieve a balance between revenue and expenses/Some public services find it challenging to break even',
    remark: 'break even break even',
  },
  {
    no: 11,
    sentence: 'We need to consider the social and economic environment',
    translationFromBook: 'We have to consider the social and economic context',
    chatgpt: 'We need to consider the social and economic environment',
    remark: '',
  },
  {
    no: 12,
    sentence: 'Density planting threatens biodiversity',
    translationFromBook: 'Intensive farming can pose a threat to bio-diversity',
    chatgpt: 'Intensive cultivation poses a threat to biodiversity',
    remark: '',
  },
  {
    no: 13,
    sentence: 'Equal access to education can help solve the problem of students’ poor academic performance',
    translationFromBook: 'Equal access to education can help tackle educational underachievement',
    chatgpt: 'Equal access to education can help tackle the issue of students\' academic underachievement',
    remark: 'Note that the to after help here can be omitted, similar to: make/let/hear/feel/watch, etc. underachievement n. low achievement; poor academic performance',
  },
  {
    no: 14,
    sentence: 'Exposure to different cultures can foster innovation',
    translationFromBook: 'Exposure to different cultures can encourage creativity',
    chatgpt: 'Exposure to different cultures can promote innovation',
    remark: 'Note that the word culture is uncountable in most cases. It can only be counted when it refers to different places or specific cultures.',
  },
  {
    no: 15,
    sentence: 'The government should pay attention to social welfare services, especially medical services',
    translationFromBook: 'The government should give priority to welfare services especially healthcare',
    chatgpt: 'The government should prioritize welfare services, especially healthcare',
    remark: '',
  },
  {
    no: 16,
    sentence: 'Education may determine one's job prospects',
    translationFromBook: 'Education may hold the key to one\'s job prospects',
    chatgpt: 'Education might shape one\'s career prospects',
    remark: 'hold the key control, control. prospects chances of success; prospects, future',
  },
  {
    no: 17,
    sentence: 'The use of fossil fuels causes environmental damage',
    translationFromBook: 'The use of fossil fuels can cause damage to the environment',
    chatgpt: 'Using fossil fuels can cause environmental damage',
    remark: 'The issue of countable and uncountable fuel refers to the general concept of fuel, which is uncountable and different types of fuel. For example, fossil fuels here may represent coal, natural gas, oil, etc...',
  },
  {
    no: 18,
    sentence: 'Building residential towers could help solve cities' congestion problems',
    translationFromBook: 'Building apartment blocks helps (to) solve overcrowding in cities',
    chatgpt: 'Constructing residential buildings helps (to) alleviate urban congestion',
    remark: 'alleviate v. alleviate; alleviate; alleviate',
  },
  {
    no: 19,
    sentence: 'Poor people can improve their social status by working hard',
    translationFromBook: 'People from disadvantaged backgrounds can improve their social status by working hard.',
    chatgpt: 'The impoverished can improve their social status through/via hard work',
    remark: '',
  },
  {
    no: 20,
    sentence: 'Because of globalization, people need to work with people from different backgrounds around the world',
    translationFromBook: 'Because of globalization, people need to work with those from diverse backgrounds',
    chatgpt: 'Due to globalization, people need to work with individuals from diverse backgrounds around the world',
    remark: 'Another expression given by ChatGPT: Due to globalization, those from diverse backgrounds around the world need to work together',
  },
  {
    no: 21,
    sentence: 'We need to take steps to solve some tough problems',
    translationFromBook: 'We need to take action to solve some thorny problems',
    chatgpt: 'We need to take measures to address some challenging issues',
    remark: 'thorny adj. Tricky, troublesome; prickly, prickly. thorn n. thorn, thorn',
  },
  {
    no: 22,
    sentence: 'The media exaggerates the pain of victims to attract viewers',
    translationFromBook: 'The media attracts public attention by sensationalizing victims\' suffering',
    chatgpt: 'The media attracts viewers by exaggerating the pain of victims',
    remark: '',
  },
  {
    no: null,
    title: 'Subject + transitive verb + object + object complement',
  },
  {
    no: 23,
    sentence: 'Genetic engineering allows people to develop new varieties of crops',
    translationFromBook: 'Genetic engineering allows people to nurture crop varieties',
    chatgpt: 'Genetic engineering allows people to cultivate new varieties of crops',
    remark: 'nurture v./n. cultivate, promote, cherish, embrace/educate, cultivate',
  },
  {
    no: 24,
    sentence: 'Companies should provide maternity leave and other assistance to female employees with children',
    translationFromBook: 'Companies should provide working mothers with maternity leave and other forms of support',
    chatgpt: 'The company should provide maternity leave and other assistance for female employees with children',
    remark: 'maternity leave maternity leave',
  },
  {
    no: 25,
    sentence: 'Unhealthy lifestyles put people at risk of illness',
    translationFromBook: 'An unhealthy lifestyle may put people at risk of illness',
    chatgpt: 'The unhealthy lifestyle puts people at risk of illness',
    remark: '',
  },
  {
    no: 26,
    sentence: 'Scholarships can encourage more students to study postgraduate courses',
    translationFromBook: 'Government grants could encourage more students to take postgraduate courses',
    chatgpt: 'Scholarships can encourage more students to pursue graduate-level/postgraduate studies',
    remark: '',
  },
  {
    no: 27,
    sentence: 'Community rehabilitation provides offenders with opportunities to gain vocational skills',
    translationFromBook: 'Community service provides offenders with opportunities to acquire transferable skills',
    chatgpt: 'The community redevelopment provides opportunities for criminals to acquire vocational skills',
    remark: '',
  },
  {
    no: 28,
    sentence: 'The law should criminalize drunk driving',
    translationFromBook: 'Legislation should make drink driving a criminal offense/offence',
    chatgpt: 'Laws should classify drunk driving as a criminal offense/offence',
    remark: 'The difference between Legislation/Laws is that Legislation generally refers to the entire legal system, while Law generally refers to specific laws. Drink/drunk driving are both reasonable expressions. The former is commonly used in the UK and the latter is used in the United States. criminal offense criminal offense, civil offense/wrong civil offense',
  },
  {
    no: 29,
    sentence: 'Rural areas offer people the opportunity to escape the stress and noise of modern life',
    translationFromBook: 'Rural areas provide people with opportunities to escape pressure and noises of modern life',
    chatgpt: 'Rural areas provide people with opportunities to escape pressure and noise of modern life - Heshu's answer is just the plural word pressure',
    remark: 'Both pressure and noise are countable and uncountable, and ChatGPT means both can be used.',
  },
  {
    no: 30,
    sentence: 'The aging of the population prompts the country to raise the statutory retirement age (statutory retirement age)',
    translationFromBook: 'The ageing population has prompted countries to raise statutory retirement age',
    chatgpt: 'The aging population is prompting the country to raise statutory retirement age',
    remark: 'Both spellings ageing and aging are acceptable.',
  },
  {
    no: null,
    title: 'Subject + transitive verb + indirect object + direct object',
  },
  {
    no: 31,
    sentence: 'The government should provide funds to some cities to protect historic buildings',
    translationFromBook: 'Governments should offer some cities funds to preserve historic buildings',
    chatgpt: 'The government should provide funds to some cities to preserve historic buildings',
    remark: '',
  },
  {
    no: null,
    title: 'passive voice',
  },
  {
    no: 32,
    sentence: 'Schools should allow teachers to force disruptive children to leave the classroom',
    translationFromBook: 'Teachers should be permitted to use force to remove the disruptive children from the classroom',
    chatgpt: 'The troublesome children should be allowed to remove from the classroom by the teachers',
    remark: '',
  },
  {
    no: 33,
    sentence: 'The unemployment problem in rural areas can be solved to some extent through rural-to-urban shift',
    translationFromBook: 'Unemployment in rural areas can be addressed partially by the rural-to-urban shift',
    chatgpt: 'The issue of unemployment in rural areas can be addressed to some extent through rural-to-urban shift',
    remark: 'in/of rural areas The difference here is in emphasizing location and of emphasizing attributes and characteristics. address/solve The former emphasizes the process of dealing with the problem rather than the definite solution to the problem, while the latter emphasizes the solution of the problem to completely solve the problem. to some extent/partially/partly can be interchanged to a certain extent',
  },
  {
    no: 34,
    sentence: 'High-rise buildings are sometimes considered an eyesore',
    translationFromBook: 'High-rise buildings are sometimes regarded as eyesores of the city',
    chatgpt: 'High-rise buildings are sometimes considered as eyesores that impact the cityscape',
    remark: 'eyesore n. (Public places) things that are unpleasant to the eyes, ugly things. consider/regard as The former emphasizes subjective and personal views, while the latter emphasizes formal and objective views.',
  },
  {
    no: 35,
    sentence: 'Investment in space technology should receive government support',
    translationFromBook: 'The investment in space technology should be supported by the government',
    chatgpt: 'Space technology investments should be supported by the government',
    remark: 'Countable nouns must be plural or have an article. Investment in means investment in a certain field is an idiomatic usage, so try to use this preposition',
  },
  {
    no: 36,
    sentence: 'Historical artifacts are preserved because of their historical importance',
    translationFromBook: 'Historic relics should be preserved for their historic significance',
    chatgpt: 'Historical artifacts are preserved due to their historical significance',
    remark: 'Historical artifacts: historical relics/artifacts. Historical significance: historical significance. historic emphasizes historical importance, and historical indicates history-related',
  },
  {
    no: 37,
    sentence: 'School activities are designed to give children a sense of accomplishment and enhance their happiness',
    translationFromBook: 'Sports or other school activities can be designed to give children a sense of accomplishment and to promote their well-being',
    chatgpt: 'A sense of achievement and an enhanced sense of happiness should be experienced by children through the arrangement of school activities',
    remark: 'school activities/design/give/a sense of accomplishment/promote/well-bing',
  },
  {
    no: 38,
    sentence: 'Some employees are encouraged to think outside the box',
    translationFromBook: 'Some employees are encouraged to break the mould',
    chatgpt: 'Some employees are encouraged to break conventions',
    remark: 'mold/mold means mold, mold, character; break the mold/mold means breaking the rules',
  },
  {
    no: 39,
    sentence: 'Because of traffic jams, commuting time has become longer.',
    translationFromBook: 'Commuting time has been prolonged because of traffic congestion',
    chatgpt: 'Due to traffic congestion, the commuting time has been extended',
    remark: 'commute v./n. commuting to and from get off work, commuting; transformation, change (payment method); commutation/commute. commuting time commuting time. prolong v. prolong, delay. have/has been done present perfect passive',
  },
  {
    no: 40,
    sentence: 'Computer skills can be applied to study and work',
    translationFromBook: 'Computer skills can be applied in their studies as well as their working lives',
    chatgpt: 'Computer skills can be applied to learning and work',
    remark: 'computer skills computer skills. apply, use in as a preposition. as well (as) = ​​in addition (to) in addition to, also, and',
  },
  {
    no: 41,
    sentence: 'Most environmental damage can be attributed to human activities',
    translationFromBook: 'Most of environmental degradation is attributed to human activities.',
    chatgpt: 'Most environmental damage can be attributed to human activities.',
    remark: 'Degradation n. Defile, damage, harm; degrade, lower status, lose face. environmental degradation environmental degradation. attribute sth. to sb./sth. Verb phrase: attribute... to; think... is produced by...; think... is the result of...',
  },
  {
    no: 42,
    sentence: 'Many children are exposed to violent content on a daily basis',
    translationFromBook: 'Many children are exposed to violent content every day',
    chatgpt: 'The first time I gave it was exactly the same as in the book, but then I changed the sentence: Many children are exposed to violent content on a daily basis',
    remark: 'expose sb. to sth. Make... suffer (harmful or unpleasant suffering); expose... to (danger). Also note that everyday adj. daily, ordinary is different from every day',
  },
  {
    no: 43,
    sentence: 'Family environment is considered to be the most important factor influencing a child’s growth',
    translationFromBook: 'The family environment is widely thought/believed to be the most important influence on children\'s development',
    chatgpt: 'The family environment is considered the most crucial influencing factor in child\'s upbringing',
    remark: 'upbringing n. raising, raising; educating, educating',
  },
  {
    no: 44,
    sentence: 'As more young people participate in volunteer work, community cohesion will be strengthened',
    translationFromBook: 'With an increasing number of young people participating in volunteer work, community cohesion will be enhanced',
    chatgpt: 'As more and more young people engage in volunteer work, the cohesion of the community will be strengthened',
    remark: 'The first half of the example in the book is a prepositional phrase as an adverbial, but the one given by ChatGPT is an adverbial clause, which is a complete sentence.',
  },
  {
    no: 45,
    sentence: 'Immigration is sometimes considered a threat to social cohesion',
    translationFromBook: 'Immigrants are sometimes recognized as a threat to social cohesion',
    chatgpt: 'Immigration is sometimes considered as a thread to social cohesion',
    remark: 'social cohesion: social cohesion',
  },
  {
    no: null,
    title: 'subject + intransitive verb',
  },
  {
    no: 46,
    sentence: 'Young people without higher education can only find low-skilled jobs',
    translationFromBook: 'Young people without tertiary education qualifications normally end up working in low-skilled jobs',
    chatgpt: 'Young people without higher education are limited to jobs with low skill requirements',
    remark: 'tertiary adj. Tertiary, tertiary; higher education, tertiary industry ~ education higher education, ~ industry tertiary industry. \n In English, "to"Prepositions are usually used to connect intransitive verbs. This is because "to" expresses concepts such as direction, goal, purpose, etc. Intransitive verbs usually require a goal or direction.',
  },
  {
    no: 47,
    sentence: 'Some people don’t support genetically modified foods',
    translationFromBook: 'Some people disapprove of genetically modified food',
    chatgpt: 'Some people do not support genetically modified (GM) foods -> This sentence is not an intransitive verb structure',
    remark: 'Transgenic: GM=genetically modified. do not and don\'t 一般前者更适合书面更正式，意思是一样的',
  },
  {
    no: 48,
    sentence: 'Tourist attractions strive to meet the needs and tastes of tourists',
    translationFromBook: 'Tourist spots endeavor to cater for tourists\' needs and tastes',
    chatgpt: 'Tourist attractions strive to meet the needs and tastes of visitors',
    remark: 'Subject + intransitive verb + to do infinitive\nAttractions: tourist spots/attractions',
  },
  {
    no: 49,
    sentence: 'In a highly competitive society, working adults tend to focus on career development',
    translationFromBook: 'In a highly competitive society, working adults usually focus on career advancement',
    chatgpt: 'In a competitive society, working adults often focus on career development',
    remark: 'advancement n. development, improvement, improvement',
  },
  {
    no: 50,
    sentence: 'Aesthetics vary depending on culture',
    translationFromBook: 'Perception of beauty differs from culture to culture',
    chatgpt: 'Aesthetic perspectives vary with cultural differences',
    remark: 'perception n. Knowledge, concept, opinion; perception, feeling; perceptual ability, cognitive ability, insight \nfrom culture to culture \n perspective n. (Thinking about the problem) angle, point of view, idea \n get/keep sth in perspective to evaluate reasonably; to look at it correctly',
  },
  {
    no: 51,
    sentence: 'The aviation industry has developed rapidly in recent decades due to falling costs.',
    translationFromBook: 'Because of low-cost carries, the aviation industry has developed at an astounding pace over the past decades',
    chatgpt: 'Due to the decrease in costs, the aviation industry has developed rapidly in recent decades',
    remark: 'astounding adj. shocking; shocking. \npace n. (moving) pace; (occurring) speed; rhythm',
  },
  {
    no: 52,
    sentence: 'Animal experiments sometimes fail to detect side effects of drugs',
    translationFromBook: 'Animal experiments sometimes fail to detect the undesirable side effects of drugs',
    chatgpt: 'The sentence given is the same as in the book, but with a different expression: At times. The use of animal experiments does not reveal the adverse effects of medications',
    remark: 'adverse adj. inseparable; negative; harmful',
  },
  {
    no: 53,
    sentence: 'Illegal hunting leads to the demise of certain animals',
    translationFromBook: 'Some animals have died out because of illegal hunting',
    chatgpt: 'Illegal hunting results in the extinction of certain animals',
    remark: 'die out gradually disappear; become extinct',
  },
  {
    no: 54,
    sentence: 'Computer impact on human communication skills changes with age',
    translationFromBook: 'The impact of computers on communication skills varies across ages',
    chatgpt: 'The impact of computers on human communication skills varies with age',
    remark: 'Across is a preposition, meaning across the surface of a certain area; cross is a verb',
  },
  {
    no: null,
    title: 'Main system table structure',
  },
  {
    no: 55,
    sentence: 'Many girls are unwilling to find a job in a male-dominated world.',
    translationFromBook: 'Many girls are not willing to seek employment in a male-dominated world',
    chatgpt: 'Many girls are unwilling to seek employment in male-dominated industries',
    remark: '',
  },
  {
    no: 56,
    sentence: 'The main function of the school is to impart knowledge to the next generation (impart knowledge)',
    translationFromBook: 'The main function of schools is to impart knowledge to the next generation',
    chatgpt: 'The primary function of schools is to impart knowledge to the next generation',
    remark: 'School is countable, so you need to add a plural or article\nChatGPT said to the next generation can be changed to for ~',
  },
  {
    no: 57,
    sentence: 'Art is not a major subject in school',
    translationFromBook: 'The arts are not among core subject areas at school',
    chatgpt: 'Art is not considered/regarded as a core subject in schools',
    remark: '',
  },
  {
    no: 58,
    sentence: 'Because the economic outlook is unclear, many companies are unlikely to hire new employees.',
    translationFromBook: 'Because of the uncertainty about he economic outlook, many companies are unlikely to recruit new employees',
    chatgpt: 'Due to the unclear economic outlook, many companies are less likely to hire new employees',
    remark: '',
  },
  {
    no: 59,
    sentence: 'Air freight can produce a lot of greenhouse gases',
    translationFromBook: 'Air freight is likely to create enormous greenhouse gases',
    chatgpt: 'Air transport may generate a significant amount of greenhouse gases',
    remark: 'freight n. Goods, freight; freight',
  },
  {
    no: 60,
    sentence: 'The child is likely to have behavioral problems',
    translationFromBook: 'Some children are likely to have behavioral/behavioural problems',
    chatgpt: 'The child is likely to have behavioral issues',
    remark: 'behavioral/behavioral writing is equivalent',
  },
  {
    no: 61,
    sentence: 'Massive population expansion is responsible for the generation of large amounts of garbage',
    translationFromBook: 'The rapid population expansion is the main reason for the huge accumulation of waste',
    chatgpt: 'The substantial expansion of population is a cause of the significant increase in waste production',
    remark: 'substantial adj. Big; considerable; huge value; significant; basically; generally',
  },
  {
    no: 62,
    sentence: 'Severe punishment is an effective means of reducing crime rates',
    translationFromBook: 'Imposing stiff punishment is an effective method to reduce crime',
    chatgpt: 'Harsh punishment is an effective means of reducing crime rates',
    remark: 'impose v. Promote; enforce; impose (especially beliefs or lifestyle) on; force; disturb; trouble',
  },
  {
    no: 63,
    sentence: 'Our environment is still very bad',
    translationFromBook: 'Our environment is still in a dire state',
    chatgpt: 'Our environment is still quite poor',
    remark: 'dire adj. Serious; critical; extreme; very bad',
  },
  {
    no: 64,
    sentence: 'College students are under pressure to study hard because of rising unemployment',
    translationFromBook: 'Undergraduates feel under increasing pressure to study hard, because of the soaring unemployment rate',
    chatgpt: 'Due to the soaring unemployment rate, college students strive to study under pressure',
    remark: 'feel is also a linking verb\nsoaring adj. towering; soaring\nstrive vi. (especially for a long time or without fear of difficulties) to work hard, struggle, strive',
  },
  {
    no: 65,
    sentence: 'Racial discrimination is still very serious',
    translationFromBook: 'Racial discrimination remains a serious problem',
    chatgpt: 'Racial discrimination remains very severe',
    remark: 'remain linking verb',
  },
  {
    no: 66,
    sentence: 'Memorizing multiplication tables is not the best way to improve your numeracy skills',
    translationFromBook: 'Learning the times table by rote is not the best way to improve numeracy',
    chatgpt: 'Rote memorization of the multiplication table is not the effective way to enhance arithmetic skills',
    remark: 'learning sth. by rote learn by rote. \nrote learning rote learning\nnumeracy n. Basic calculation ability, number recognition',
  },
  {
    no: 67,
    sentence: 'The first priority of poor countries is to meet people's basic survival needs',
    translationFromBook: 'The top priority for deprived countries is to satisfy citizens\' basic needs',
    chatgpt: 'The primary task of impoverished nations is to meet the basic survival needs of their people',
    remark: 'deprive v. take away, snatch away, deprive. \ndeprived adj. Shortage, lack; poor. a ~ area Poverty-stricken area. \nimpoverished adj. Extremely poor; (quality) deteriorated. \nsurvive is a verb',
  },
  {
    no: 68,
    sentence: 'The health effects of genetically modified foods remain unknown',
    translationFromBook: 'The health effect of GE food remains unclear/yet to be known',
    chatgpt: 'The impact of genetically modified food on health remains uncertain',
    remark: 'GE=genetically engineered also means genetically modified and has the same meaning as the previous GM.',
  },
  {
    no: 69,
    sentence: 'Online shopping has become a common part of many people's daily lives',
    translationFromBook: 'Online shopping has become a normal part of people\'s everyday life.',
    chatgpt: 'Online shopping has become a commonplace aspect of many people\'s daily lives',
    remark: 'become/became/become simple tense/past tense/past participle. \ncommonplace adj./n. Ordinary; common; ordinary; common/cliché; cliché. \nThe plural form of life lives',
  },
  {
    no: 70,
    sentence: 'In a consumer society, people are no longer satisfied with bare necessities.',
    translationFromBook: 'In the consumer society, bare necessities are not able to satisfy people\'s needs',
    chatgpt: 'In consumer society, people are no longer satisfied with just the bare necessities of life',
    remark: 'the bare necessities necessities of life',
  },
  {
    no: 71,
    sentence: 'People’s unhealthy lifestyles are a result of their tendency to rely on technology',
    translationFromBook: 'People\'s unhealthy lifestyle is the result of their tendency to rely heavily on technology',
    chatgpt: 'Unhealthy lifestyles among people are a result of their tendency to rely on technology',
    remark: 'tendency n. (the tendency of thoughts, behaviors, etc.); trend',
  },
  {
    no: 72,
    sentence: 'Poverty causes increased crime in communities',
    translationFromBook: 'Poverty is the reason of the crime wave in many communities',
    chatgpt: 'Poverty is a contributing factor of the increase in community crime',
    remark: 'crime wave n. surge in crime rate',
  },
  {
    no: 73,
    sentence: 'The invention of electric cars is part of our efforts to protect the environment',
    translationFromBook: 'The invention of electric vehicles is a part of our effort to sustain the environment',
    chatgpt: 'The invention of electric cars is part of our efforts to preserve the environment',
    remark: '',
  },
  {
    no: null,
    title: 'Sentences in which it serves as formal subject or formal object',
  },
  {
    no: 74,
    sentence: 'Giving lavish gifts is a Chinese habit',
    translationFromBook: 'It is very common for Chinese people to exchange lavish gifts',
    chatgpt: 'It is a Chinese custom to give lavish gifts',
    remark: '',
  },
  {
    no: 75,
    sentence: 'It will be difficult to protect plant diversity in the coming decades',
    translationFromBook: 'We will find it difficult to preserve biodiversity in the coming decades',
    chatgpt: 'In the coming decades, it will be challenging to preserve plant biodiversity',
    remark: 'biodiversity n. biological diversity',
  },
  {
    no: 76,
    sentence: 'As people age, it becomes more difficult to stay in touch with family and friends',
    translationFromBook: 'With age, people find it difficult to maintain contact with family and friends',
    chatgpt: 'As people grow older, it becomes difficult to stay in touch with family and friends',
    remark: 'with age/grow older',
  },
  {
    no: 77,
    sentence: 'Free college education allows students from disadvantaged backgrounds to have equal access to school',
    translationFromBook: 'Free university education makes it possible for students from less well-off backgrounds to have equal access to tertiary education',
    chatgpt: 'Free university education provides equal opportunities for students from disadvantaged backgrounds to attend college',
    remark: 'well off adj. rich',
  },
  {
    no: 78,
    sentence: 'Many people feel the need to follow trends',
    translationFromBook: 'Many people consider it necessary to follow fashion',
    chatgpt: 'Many people feel it necessary to keep up trends',
    remark: '',
  },
  {
    no: 79,
    sentence: 'Funding cuts make it difficult for many young people to get a university education',
    translationFromBook: 'Budget cuts make it difficult for many young people to receive a college education',
    chatgpt: 'Budget cuts make it difficult for many young people to afford a college education',
    remark: 'budget cuts budget cuts',
  },
  {
    no: 80,
    sentence: 'It is sometimes difficult to assess the environmental costs of human actions',
    translationFromBook: 'Sometimes, it is difficult to evaluate the environmental cost of human activities',
    chatgpt: 'Sometimes, it is difficult to assess the environmental costs of human behavior',
    remark: 'behavior uncountable',
  },
  {
    no: null,
    title: 'there be sentence pattern',
  },
  {
    no: 81,
    sentence: 'There are some poor communities in big cities',
    translationFromBook: 'There are some economically deprived communities in large cities',
    chatgpt: 'There are some impoverished communities in big cities',
    remark: 'economically deprived economically deprived. deprived adj./v. poor/deprived',
  },
  {
    no: 82,
    sentence: 'There is no obvious connection between class placement according to ability and student performance.',
    translationFromBook: 'There is no clear link between grouping students by ability and their levels of attainments',
    chatgpt: 'There is no clear correlation between ability-based grouping and students\' grades',
    remark: 'attainment n. Realization, acquisition, winning; achievement, attainment\ncorrelation n. Interconnection; practice; correlation',
  },
  {
    no: null,
    title: 'parallel sentences',
  },
  {
    no: 83,
    sentence: 'Using multimedia can increase students' attention and keep them interested in the course',
    translationFromBook: 'Using multimedia tools can improve students\'s concentration and keep them interested',
    chatgpt: 'Using multimedia can enhance students\' attention and keep them interested in the course',
    remark: '',
  },
  {
    no: 84,
    sentence: 'Celebrities’ achievements encourage young people to study hard and persevere',
    translationFromBook: 'The achievement of celebrities can motivate young people to study hard and show perseverance',
    chatgpt: 'The achievements of celebrities inspire young people to study hard and persevere (Here ChatGPT is translated into 2 verbs juxtaposed inspire/preserve)',
    remark: 'perseverance n. perseverance, perseverance',
  },
  {
    no: 85,
    sentence: 'Opening new branches in developing countries can reduce production costs and generate huge profits',
    translationFromBook: 'Opening new branches in developing countries can reduce the cost of production and generate huge profits',
    chatgpt: 'Opening new branches in developing countries can reduce production costs and generate significant profits',
    remark: 'in developing countries is a fixed phrase rather than in the ~',
  },
  {
    no: 86,
    sentence: 'Slight lifestyle changes can make a huge difference and reduce the environmental impact of our daily activities',
    translationFromBook: 'Small lifestyle changes can make a huge difference and reduce the environmental impact of our daily activities',
    chatgpt: 'Slight changes in lifestyle can make a huge difference and reduce the impact of our daily activities on the environment',
    remark: '',
  },
  {
    no: null,
    title: 'adverbial clause',
  },
  {
    no: 87,
    sentence: 'Because there are no internship opportunities, it is difficult for students to improve their work skills.',
    translationFromBook: 'It is difficult for students to improve practical skills if school do not provide work placements',
    chatgpt: 'Without internship opportunities, it is difficult for students to enhance their job skills',
    remark: 'work placement n. work internship\ninternship n. internship period',
  },
  {
    no: 88,
    sentence: 'Even if you get a diploma, college students can't make a lot of money',
    translationFromBook: 'University students cannot make a decent living even though they have gained qualifications',
    chatgpt: 'Even with a diploma, college students may not be able to earn a lot of money',
    remark: '',
  },
  {
    no: 89,
    sentence: '因为激烈的竞争和技术的迅速发展，现在经营一家公司是一个艰巨的任务',
    translationFromBook: 'Running an organization in today\'s world can be a daunting task because competition is stiff and technology is developing rapidly',
    chatgpt: 'Running a company is a daunting task in today\'s world, due to fierce competition and rapid technological advancement —— from Gemini',
    remark: 'daunting adj. daunting; discouraging\nadvancement n. development, improvement, improvement',
  },
  {
    no: null,
    title: 'noun clause',
  },
  {
    no: 90,
    sentence: 'The fact is that some jobs have been eliminated because of mechanization',
    translationFromBook: 'The fact is that some jobs have been made redundant because of mechanization',
    chatgpt: 'The fact is that some jobs have been eliminated due to mechanization',
    remark: 'redundant adj. (words, phrases, etc.) redundant, unnecessary; unemployed, laid off\nmechanization n. mechanization\neliminate v. eliminate, kill, eliminate',
  },
  {
    no: 91,
    sentence: 'Nowadays many people are choosing to go green and reduce their energy usage and it is true',
    translationFromBook: 'It is true that many people today have chosen to go green and reduce cut down on the use of energy',
    chatgpt: 'It is true that many people are now choosing to be environmentally friendly and reduce their energy consumption',
    remark: '',
  },
  {
    no: 92,
    sentence: 'Sentences can harm young people as criminal records can cast a shadow on their careers',
    translationFromBook: ' A prison sentence can be damaging to young people due to the fact that the criminal record can cast a long shadow on their career',
    chatgpt: 'A criminal conviction can have a harmful impact on a young person\'s life, as it can leave a criminal record that can follow then throughout their career',
    remark: 'cast v. cast (light or shadow) towards, project\nconviction n. condemn, convict\nthroughout prep./adv. everywhere, from beginning to end',
  },
  {
    no: 93,
    sentence: 'I believe there is a direct correlation between fast food advertising and widespread obesity',
    translationFromBook: 'I believe that there is a direct link between fast food advertisements and rising levels of obesity',
    chatgpt: 'I believe that there is a direct relationship between fast food advertising and obesity',
    remark: 'obesity n. obesity',
  },
  {
    no: null,
    title: 'attributive clause',
  },
  {
    no: 94,
    sentence: 'Spending government money on pollution cleanup could create a more comfortable environment',
    translationFromBook: 'Money can be used for clean-up operation which can help create a pleasant environment',
    chatgpt: 'Directing government funding towards pollution cleanup efforts can create a more livable environment',
    remark: '',
  },
  {
    no: 95,
    sentence: 'Some advertisements encourage consumers to buy things they don’t need, and controls should be tightened on them',
    translationFromBook: 'It is necessary to put/impose restrictions on those advertisements which encourage people to buy more than they need',
    chatgpt: 'Some advertisements, which encourage consumers to buy things they don\'t need, should be subject to stricter regulation',
    remark: 'be subject to something; suffer; endure',
  },
  {
    no: 96,
    sentence: 'Planting trees can help improve air quality, thereby reducing the risk of some diseases, such as respiratory illnesses',
    translationFromBook: 'Afforestation can help to improve air quality, which can reduce the risk of suffering health problems such as respiratory diseases',
    chatgpt: 'Afforestation helps improve air quality, thereby reducing the risk of certain diseases, such as respiratory illnesses',
    remark: 'afforestation n. afforestation\nrespiratory adj. respiratory',
  },
  {
    no: 97,
    sentence: 'The government should control news that exaggerates social issues',
    translationFromBook: 'Authorities should censor those news reports which give an exaggerated account of some social problems',
    chatgpt: 'The government should control the news that exaggerates social issues',
    remark: 'exaggerate v. exaggerate, exaggerate, exaggerate...',
  },
  {
    no: 98,
    sentence: 'This is why today’s clerks often have health problems',
    translationFromBook: 'It is the reason why clerical workers today suffer health problems',
    chatgpt: 'This is why clerical workers often experience health issues nowadays',
    remark: 'clerical adj. office, clerical work; pastor; clergy',
  },
  {
    no: 99,
    sentence: 'Many employees are willing to work for companies that offer advancement opportunities',
    translationFromBook: 'Many employees are willing to work for companies where they can obtain promotional opportunities',
    chatgpt: 'Many employees are willing to work in companies where they can get opportunities for promotion',
    remark: '',
  },
  {
    no: 100,
    sentence: 'Many young people choose to study in English-speaking countries, where they can study at world-renowned universities',
    translationFromBook: 'Many young people have chosen to study in English-speaking countries, where they can study at some world famous universities',
    chatgpt: 'Many young people choose to study in English-speaking countries where they can attend world-renowned universities',
    remark: 'world-renowned adj. (in a certain field) world-renowned',
  },
]

export default sentences
